# Generated by Django 3.0.8 on 2020-07-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_auto_20200725_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='snippet', max_length=255),
        ),
    ]
