# Generated by Django 3.0.8 on 2020-08-01 08:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_auto_20200730_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=350),
        ),
    ]
